# Generated by Django 2.2.3 on 2019-07-17 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adjust_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analytics',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
